version: '2'
services:
  php:
    build: ./server/php
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
  nginx:
    build: ./server/nginx
    working_dir: /var/www
    volumes_from:
      - php
    ports:
      - 80:80

  database:
    image: mysql:8.0
    volumes:
      - ./server/mysql:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=app"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=app@"
      - "MYSQL_ROOT_PASSWORD=root@"
    ports:
      - "3306:3306"